language: node_js

node_js:
  - "0.12"
  - "0.10"

before_install:
  - npm install -g gulp
  - npm install -g browserify
  - npm install -g testem

install:
  - npm install

script:
  - gulp test
  - gulp linter
  - NODE_ENV=production gulp build-app
#  e2e
  - browserify test/travis/schemas.spec.js -o bundle.js -s pojoviz && testem ci