language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g gulp vulcanize bower
#  - npm install -g browserify testem

install:
  - npm install
  - bower install

script:
  - gulp test
  - gulp linter
  - gulp polymer
  - NODE_ENV=production gulp build
#  ci test
  - browserify test/ci/schemas.spec.js -o test/ci/bundle.js -s pojoviz
  - gulp test:ci