language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g gulp browserify testem

install:
  - npm install

script:
  - gulp test
  - gulp linter
  - gulp polymer
  - NODE_ENV=production gulp build
#  e2e
#  - browserify test/travis/schemas.spec.js -o bundle.js -s pojoviz
#  - testem launchers
#  - testem ci