language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g gulp

install:
  - npm install --production

before_script:
  - npm install gulp-mocha
  - npm install chai
  - npm install jshint
  - npm install jshint-stylish

script:
  - gulp test
  - gulp linter
  - gulp build-app

env:
  - NODE_ENV=production